# stats available at
# https://travis-ci.org/strukturag/libde265/
language: cpp
compiler:
  - clang
  - gcc
env:
  - HOST= WINE= DECODESTREAMS=
  - HOST= WINE= DECODESTREAMS=1
  - HOST=i686-w64-mingw32 WINE=wine DECODESTREAMS=
  - HOST=x86_64-w64-mingw32 WINE=wine64 DECODESTREAMS=

matrix:
  exclude:
    - compiler: clang
      env: HOST= WINE= DECODESTREAMS=
    - compiler: clang
      env: HOST=i686-w64-mingw32 WINE=wine DECODESTREAMS=
    - compiler: clang
      env: HOST=x86_64-w64-mingw32 WINE=wine64 DECODESTREAMS=

before_install:
  - sh -c "if [ '$DECODESTREAMS' = '1' ]; then sudo add-apt-repository -y ppa:strukturag/libde265; fi"
  - sudo apt-get update -qq
  - sh -c "if [ -z '$HOST' ]; then sudo apt-get install -qq valgrind libsdl-dev; fi"
  - sh -c "if [ ! -z '$HOST' ]; then sudo apt-get install -qq wine; fi"
  - sh -c "if [ '$WINE' = 'wine'   ]; then sudo apt-get install -qq gcc-mingw-w64-i686   g++-mingw-w64-i686   binutils-mingw-w64-i686   mingw-w64-dev; fi"
  - sh -c "if [ '$WINE' = 'wine64' ]; then sudo apt-get install -qq gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev; fi"
  - sh -c "if [ '$DECODESTREAMS' = '1' ]; then sudo apt-get install -qq libde265-teststreams; fi"

install:
  - git clone https://github.com/strukturag/libde265-data.git

before_script:
  - ./autogen.sh
  - if [ ! -z "$HOST" ]; then unset CC; fi
  - if [ ! -z "$HOST" ]; then unset CXX; fi
  - ./configure --host=$HOST

script:
  - make
  - sh -c "if [ -z "$HOST" ] && [ -z "$DECODESTREAMS" ]; then LD_LIBRARY_PATH=./libde265/.libs/ valgrind --tool=memcheck --quiet --error-exitcode=1 ./dec265/.libs/dec265 -q -c -f 100 ./libde265-data/IDR-only/paris-352x288-intra.bin; fi"
  - sh -c "if [ -z "$HOST" ] && [ -z "$DECODESTREAMS" ]; then LD_LIBRARY_PATH=./libde265/.libs/ valgrind --tool=memcheck --quiet --error-exitcode=1 ./dec265/.libs/dec265 -t 4 -q -c -f 100 ./libde265-data/IDR-only/paris-352x288-intra.bin; fi"
  - sh -c "if [ -z "$HOST" ] && [ -z "$DECODESTREAMS" ]; then LD_LIBRARY_PATH=./libde265/.libs/ valgrind --tool=memcheck --quiet --error-exitcode=1 ./dec265/.libs/dec265 -q -c -f 100 ./libde265-data/RandomAccess/paris-ra-wpp.bin; fi"
  - sh -c "if [ -z "$HOST" ] && [ -z "$DECODESTREAMS" ]; then LD_LIBRARY_PATH=./libde265/.libs/ valgrind --tool=memcheck --quiet --error-exitcode=1 ./dec265/.libs/dec265 -t 4 -q -c -f 100 ./libde265-data/RandomAccess/paris-ra-wpp.bin; fi"
  - sh -c "if [ ! -z "$HOST" ]; then WINEPREFIX=`pwd`/$WINE $WINE ./dec265/dec265.exe -q -c ./libde265-data/IDR-only/paris-352x288-intra.bin; fi"
  - sh -c "if [ ! -z "$HOST" ]; then WINEPREFIX=`pwd`/$WINE $WINE ./dec265/dec265.exe -t 4 -q -c ./libde265-data/IDR-only/paris-352x288-intra.bin; fi"
  - sh -c "if [ ! -z "$HOST" ]; then WINEPREFIX=`pwd`/$WINE $WINE ./dec265/dec265.exe -q -c ./libde265-data/RandomAccess/paris-ra-wpp.bin; fi"
  - sh -c "if [ ! -z "$HOST" ]; then WINEPREFIX=`pwd`/$WINE $WINE ./dec265/dec265.exe -t 4 -q -c ./libde265-data/RandomAccess/paris-ra-wpp.bin; fi"
  - sh -c "if [ '$DECODESTREAMS' = '1' ]; then python scripts/decodestreams.py /var/lib/libde265-teststreams; fi"
