# stats available at
# https://ci.appveyor.com/project/strukturag/libde265
image: Visual Studio 2019
configuration: Release

environment:
  matrix:
  - arch: x64

install:
  - git clone --depth 1 https://github.com/strukturag/libde265-data.git

before_build:
  - mkdir build
  - cd build
  - cmake .. -A %arch%

build:
  verbosity: normal

before_test:
  - copy /y dec265\%CONFIGURATION%\dec265.exe .
  - copy /y enc265\%CONFIGURATION%\enc265.exe .
  - copy /y libde265\%CONFIGURATION%\libde265.dll .

test_script:
  - dec265.exe -q -c -f 100 ..\libde265-data\IDR-only\paris-352x288-intra.bin
  - dec265.exe -t 4 -q -c -f 100 ..\libde265-data\IDR-only\paris-352x288-intra.bin
  - dec265.exe -q -c -f 100 ..\libde265-data\RandomAccess\paris-ra-wpp.bin
  - dec265.exe -t 4 -q -c -f 100 ..\libde265-data\RandomAccess\paris-ra-wpp.bin

artifacts:
  - path: build
  - path: build\**\Release\*.exe
  - path: build\**\Release\*.dll
