name: coverity

on:
  push:
    branches: [ coverity ]

jobs:
  scan:
    runs-on: ubuntu-22.04
    env:
      TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - name: Cache Coverity build tool
      uses: actions/cache@v5
      with:
        path: |
          coverity_tool.tar.gz
        key: ${{ runner.os }}

    - name: Download Coverity build tool
      run: |
        wget -c -N https://scan.coverity.com/download/linux64 --post-data "token=$TOKEN&project=libde265" -O coverity_tool.tar.gz
        mkdir coverity_tool
        tar xzf coverity_tool.tar.gz --strip 1 -C coverity_tool

    - name: Install dependencies
      run: |
        ./scripts/ci-before-install-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/ci-before-script.sh

    - name: Build with Coverity build tool
      run: |
        export PATH=`pwd`/coverity_tool/bin:$PATH
        cov-build --dir cov-int make

    - name: Submit build result to Coverity Scan
      run: |
        tar czvf libde265.tar.gz cov-int
        curl --form token=$TOKEN \
          --form email=opensource@struktur.de \
          --form file=@libde265.tar.gz \
          --form version="Commit $GITHUB_SHA" \
          --form description="Build submitted via CI" \
          https://scan.coverity.com/builds?project=libde265
