name: mingw

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        env:
          - { TARGET_HOST: "i686-w64-mingw32", WINE: "wine" }
          - { TARGET_HOST: "x86_64-w64-mingw32", WINE: "wine64" }
    env: ${{ matrix.env }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Checkout sample streams
      uses: actions/checkout@v4
      with:
        repository: strukturag/libde265-data
        path: libde265-data

    - name: Install dependencies
      run: |
        ./scripts/ci-before-install-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/ci-before-script.sh

    - name: Run tests
      run: |
        ./scripts/ci-run.sh
